"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os
import dj_database_url  # Import library database railway
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SECURITY CONFIGURATION ---
# SECRET_KEY: Di production sebaiknya pakai Environment Variable, tapi untuk belajar hardcode tidak apa-apa
SECRET_KEY = 'django-insecure-3r!95b=+1g+g)3g19hw=u8s%^=wr8i7*ac3i(nf1hbsgt^hbyb'

# DEBUG: Biarkan True agar mudah debug error. Nanti di Railway set variable DEBUG=False jika sudah pro.
DEBUG = True

# Izinkan semua host (Penting untuk Railway)
ALLOWED_HOSTS = ['*']


# --- APPLICATION DEFINITION ---

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Library Pihak Ketiga
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Apps Kita
    'users',
    'inventory',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',         # Paling atas (rekomendasi)
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',    # Di bawah SecurityMiddleware (Untuk Static File Railway)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# --- DATABASE CONFIGURATION ---
# Default pakai SQLite (Untuk Lokal)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Jika terdeteksi ada DATABASE_URL (Environment Variable dari Railway), pakai PostgreSQL
database_url = os.environ.get("DATABASE_URL")
if database_url:
    DATABASES['default'] = dj_database_url.parse(database_url)


# --- PASSWORD VALIDATION ---
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# --- INTERNATIONALIZATION ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- STATIC FILES (CSS, JS, IMAGES) ---
# WhiteNoise membutuhkan konfigurasi ini agar admin panel tidak berantakan di Railway

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# --- MEDIA FILES (UPLOAD USER) ---
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# --- REST FRAMEWORK ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}


# --- CORS & CSRF (AGAR FRONTEND BISA AKSES) ---

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite Localhost
    "http://localhost:3000",  # React Default
    "https://simig-webapps-production.up.railway.app",
    # Tambahkan URL Frontend Railway kamu nanti di sini setelah deploy
    # Contoh: "https://simig-frontend.up.railway.app"
]

# Penting untuk Railway agar tidak kena error "CSRF Failed: Origin checking failed"
CSRF_TRUSTED_ORIGINS = [
    "https://*.railway.app", 
]


# --- CUSTOM USER MODEL ---
AUTH_USER_MODEL = 'users.User'

# --- DEFAULT PRIMARY KEY ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- KONFIGURASI JWT (AGAR TIDAK CEPAT LOGOUT) ---
SIMPLE_JWT = {
    # Ini kuncinya: Ganti umur Access Token jadi lama (misal 1 hari)
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), 

    # Umur Refresh token (opsional, set lebih lama)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Settingan standar lainnya
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}