# Generated by Django 6.0 on 2026-01-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_transactionout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Berat di Gudang (Kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionin',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Jumlah Masuk (Kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionout',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Jumlah Keluar (Kg)', max_digits=10),
        ),
    ]
