# Generated by Django 6.0 on 2026-01-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_stock_alter_product_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Berat dalam Kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionin',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionout',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
